language:
    - python
python:
    - "2.7"

notifications:
  email: false

virtualenv:
  system_site_packages: true


before_install:
    - "sudo apt-get install -qq python-scipy"

# command to install dependencies
install:
    - "mkdir tests/dcase2016/"
    - "cd tests/dcase2016/"
    - "wget https://github.com/TUT-ARG/DCASE2016-baseline-system-python/archive/v1.0.6.zip"
    - "unzip v1.0.6.zip"
    - "cd ../../"
    - "pip install -r requirements.txt"
    - "pip install python-coveralls"
    - "pip install coveralls"
    - "pip install nose"
    - "python setup.py develop"

# command to run tests
script:
    - "nosetests --with-coverage --cover-erase --cover-package=sed_eval -v -w tests/"

after_success:
    - "coveralls"
    - "python setup.py develop --uninstall"

after_failure:
    - "python setup.py develop --uninstall"